import type { Metadata } from "next";
import { ClerkProvider, SignUp, SignedIn, SignedOut, GoogleOneTap } from '@clerk/nextjs'
import PrelineScript from "./components/PrelineScript";
import Navigation from "./components/Navigation";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@xyflow/react/dist/style.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Milt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <GoogleOneTap />

          <SignedIn >
            <div className="h-screen flex flex-col dark:bg-neutral-800 dark:border-neutral-700 bg-[url('https://preline.co/assets/svg/component/hero-gradient.svg')]">
              <Navigation />
              <main className='max-w-screen-lg m-auto w-full  grow flex justify-center mt-6 p-4'>{children}</main>
            </div>
          </SignedIn>

          <SignedOut>
            <div className="flex justify-center min-h-screen items-center">
              <SignUp />
            </div>
          </SignedOut>
          <PrelineScript />
        </body>
      </html>
    </ClerkProvider>
  );
}
